-- Assets data generated on 2025-03-22 18:22:39.818542

INSERT INTO assets (name, asset_type, broker_id) VALUES
('American Solutions Bond 15yr', 'Bond', 4),
('Bitcoin', 'Cryptocurrency', 8),
('NASDAQ Select ETF', 'ETF', 5),
('Litecoin', 'Cryptocurrency', 6),
('Smart Commodity', 'Commodity', 4),
('Global Options', 'Options', 16),
('Quantum Healthcare', 'Stock', 1),
('Litecoin', 'Cryptocurrency', 15),
('Pacific Futures', 'Futures', 7),
('Smart Commodity', 'Commodity', 15),
('Quantum Commodity', 'Commodity', 7),
('Smart Futures', 'Futures', 20),
('Litecoin', 'Cryptocurrency', 16),
('Litecoin', 'Cryptocurrency', 9),
('DOW Select ETF', 'ETF', 11),
('Litecoin', 'Cryptocurrency', 25),
('S&P Prime ETF', 'ETF', 20),
('Pacific Commodity', 'Commodity', 17),
('Ethcoin', 'Cryptocurrency', 27),
('Tech Commodity', 'Commodity', 27),
('Bio Ltd Bond 17yr', 'Bond', 22),
('Bitcoin', 'Cryptocurrency', 8),
('United Options', 'Options', 25),
('Atlantic Commodity', 'Commodity', 1),
('Quantum Futures', 'Futures', 22),
('Alpine Inc', 'Stock', 4),
('Pacific Inc', 'Stock', 24),
('Euro Inc', 'Stock', 18),
('NASDAQ Total ETF', 'ETF', 30),
('Smart Tech Bond 14yr', 'Bond', 3),
('Bitcoin', 'Cryptocurrency', 40),
('American Commodity', 'Commodity', 39),
('Ethcoin', 'Cryptocurrency', 31),
('United Options', 'Options', 25),
('Litecoin', 'Cryptocurrency', 11),
('Tech Media Bond 28yr', 'Bond', 18),
('Asia Communications', 'Stock', 11),
('Euro Commodity', 'Commodity', 13),
('Alpine Futures', 'Futures', 44),
('Global Commodity', 'Commodity', 2),
('Tech Industries Bond 13yr', 'Bond', 34),
('Bio Industries', 'Stock', 13),
('Alpine Corp', 'Stock', 6),
('Quantum Commodity', 'Commodity', 42),
('S&P Total ETF', 'ETF', 31),
('Eco Futures', 'Futures', 19),
('Cyber Solutions Bond 16yr', 'Bond', 7),
('Smart Healthcare', 'Stock', 12),
('American Futures', 'Futures', 28),
('Cyber Healthcare Bond 23yr', 'Bond', 4),
('S&P Prime ETF', 'ETF', 18),
('S&P Select ETF', 'ETF', 60),
('Asia Commodity', 'Commodity', 40),
('Pacific Solutions', 'Stock', 1),
('American Networks', 'Stock', 30),
('DOW Prime ETF', 'ETF', 10),
('Asia Corp Bond 4yr', 'Bond', 2),
('Eco Futures', 'Futures', 68),
('Bitcoin', 'Cryptocurrency', 3),
('Atlantic Futures', 'Futures', 14),
('Ethcoin', 'Cryptocurrency', 56),
('Pacific Futures', 'Futures', 65),
('Tech Futures', 'Futures', 17),
('Global Options', 'Options', 14),
('Euro Inc Bond 7yr', 'Bond', 59),
('Bitcoin', 'Cryptocurrency', 41),
('Digital Futures', 'Futures', 53),
('S&P Prime ETF', 'ETF', 28),
('Pacific Options', 'Options', 24),
('Global Ltd', 'Stock', 65),
('Bio Futures', 'Futures', 27),
('Pacific Commodity', 'Commodity', 43),
('NASDAQ Select ETF', 'ETF', 53),
('Smart Futures', 'Futures', 81),
('Asia Pharma', 'Stock', 66),
('Pacific Futures', 'Futures', 60),
('S&P Select ETF', 'ETF', 47),
('Bio Options', 'Options', 63),
('Cyber Systems', 'Stock', 72),
('S&P Prime ETF', 'ETF', 33),
('Bio Industries Bond 21yr', 'Bond', 77),
('Cyber Options', 'Options', 85),
('Atlantic Futures', 'Futures', 25),
('Bitcoin', 'Cryptocurrency', 77),
('Global Commodity', 'Commodity', 64),
('S&P Total ETF', 'ETF', 72),
('Smart Pharma Bond 14yr', 'Bond', 17),
('Global Networks Bond 19yr', 'Bond', 62),
('Litecoin', 'Cryptocurrency', 73),
('DOW Total ETF', 'ETF', 66),
('Tech Pharma Bond 19yr', 'Bond', 17),
('Ethcoin', 'Cryptocurrency', 36),
('Bio Group', 'Stock', 49),
('American Energy', 'Stock', 70),
('Global Futures', 'Futures', 51),
('Bitcoin', 'Cryptocurrency', 55),
('Cyber Systems', 'Stock', 26),
('United Options', 'Options', 108),
('S&P Select ETF', 'ETF', 55),
('American Commodity', 'Commodity', 49),
('Bio Commodity', 'Commodity', 14),
('Global Futures', 'Futures', 88),
('Litecoin', 'Cryptocurrency', 60),
('Litecoin', 'Cryptocurrency', 72),
('American Media', 'Stock', 35),
('Bitcoin', 'Cryptocurrency', 79),
('Bitcoin', 'Cryptocurrency', 1),
('Global Options', 'Options', 71),
('Ethcoin', 'Cryptocurrency', 8),
('Global Options', 'Options', 103),
('Smart Options', 'Options', 69),
('Quantum Industries Bond 12yr', 'Bond', 47),
('NASDAQ Select ETF', 'ETF', 39),
('Smart Group Bond 4yr', 'Bond', 29),
('Tech Corp Bond 15yr', 'Bond', 11),
('Quantum Healthcare Bond 24yr', 'Bond', 88),
('Digital Networks', 'Stock', 55),
('American Commodity', 'Commodity', 110),
('Bitcoin', 'Cryptocurrency', 3),
('Ethcoin', 'Cryptocurrency', 49),
('Quantum Ltd Bond 15yr', 'Bond', 1),
('Alpine Futures', 'Futures', 76),
('Smart Futures', 'Futures', 41),
('Eco Systems', 'Stock', 69),
('Quantum Futures', 'Futures', 115);

INSERT INTO assets (name, asset_type, broker_id) VALUES
('Tech Commodity', 'Commodity', 128),
('Euro Options', 'Options', 45),
('Quantum Tech', 'Stock', 157),
('Bio Media', 'Stock', 171),
('NASDAQ Total ETF', 'ETF', 197),
('Tech Futures', 'Futures', 209),
('Smart Communications Bond 3yr', 'Bond', 160),
('NASDAQ Prime ETF', 'ETF', 45),
('Atlantic Options', 'Options', 8),
('Litecoin', 'Cryptocurrency', 79),
('Eco Options', 'Options', 101),
('Quantum Commodity', 'Commodity', 40),
('Digital Energy Bond 29yr', 'Bond', 254),
('Tech Options', 'Options', 95),
('Atlantic Solutions', 'Stock', 221),
('Quantum Futures', 'Futures', 139),
('Ethcoin', 'Cryptocurrency', 59),
('Digital Healthcare', 'Stock', 203),
('Atlantic Networks', 'Stock', 52),
('Alpine Options', 'Options', 82),
('Smart Networks Bond 9yr', 'Bond', 27),
('Asia Group', 'Stock', 210),
('Smart Futures', 'Futures', 256),
('Bitcoin', 'Cryptocurrency', 100),
('Bio Commodity', 'Commodity', 105),
('DOW Select ETF', 'ETF', 194),
('S&P Total ETF', 'ETF', 42),
('Tech Options', 'Options', 205),
('Bitcoin', 'Cryptocurrency', 259),
('Tech Options', 'Options', 2),
('Atlantic Commodity', 'Commodity', 272),
('Litecoin', 'Cryptocurrency', 95),
('Euro Options', 'Options', 174),
('Cyber Commodity', 'Commodity', 177),
('Pacific Tech', 'Stock', 286),
('NASDAQ Select ETF', 'ETF', 290),
('Bitcoin', 'Cryptocurrency', 229),
('Litecoin', 'Cryptocurrency', 250),
('Asia Commodity', 'Commodity', 59),
('NASDAQ Prime ETF', 'ETF', 272),
('Bitcoin', 'Cryptocurrency', 61),
('Cyber Commodity', 'Commodity', 146),
('Pacific Group Bond 12yr', 'Bond', 36),
('Bitcoin', 'Cryptocurrency', 192),
('United Commodity', 'Commodity', 184),
('Alpine Communications', 'Stock', 73),
('NASDAQ Select ETF', 'ETF', 281),
('Pacific Options', 'Options', 63),
('United Options', 'Options', 154),
('NASDAQ Total ETF', 'ETF', 172),
('Bio Ltd Bond 13yr', 'Bond', 52),
('Bio Media Bond 26yr', 'Bond', 213),
('Smart Communications', 'Stock', 65),
('Euro Media', 'Stock', 276),
('Digital Media', 'Stock', 18),
('Atlantic Futures', 'Futures', 101),
('Asia Communications', 'Stock', 317),
('Global Options', 'Options', 120),
('Bitcoin', 'Cryptocurrency', 13),
('Litecoin', 'Cryptocurrency', 216),
('Asia Ltd Bond 7yr', 'Bond', 95),
('NASDAQ Total ETF', 'ETF', 273),
('Eco Communications', 'Stock', 127),
('NASDAQ Select ETF', 'ETF', 142),
('American Options', 'Options', 106),
('Cyber Media Bond 8yr', 'Bond', 97),
('Bio Energy', 'Stock', 175),
('United Inc Bond 25yr', 'Bond', 299),
('Atlantic Commodity', 'Commodity', 94),
('NASDAQ Select ETF', 'ETF', 330),
('Alpine Futures', 'Futures', 113),
('Euro Systems', 'Stock', 303),
('Quantum Options', 'Options', 39),
('Euro Corp', 'Stock', 109),
('Quantum Commodity', 'Commodity', 238),
('Pacific Networks Bond 14yr', 'Bond', 23),
('Bio Pharma', 'Stock', 292),
('Global Media Bond 29yr', 'Bond', 329),
('Cyber Futures', 'Futures', 241),
('Litecoin', 'Cryptocurrency', 183),
('Eco Futures', 'Futures', 319),
('Euro Futures', 'Futures', 264),
('Tech Commodity', 'Commodity', 107),
('Digital Industries Bond 5yr', 'Bond', 194),
('NASDAQ Prime ETF', 'ETF', 339),
('Ethcoin', 'Cryptocurrency', 229),
('Tech Options', 'Options', 308),
('Litecoin', 'Cryptocurrency', 256),
('NASDAQ Prime ETF', 'ETF', 329),
('Global Futures', 'Futures', 232),
('American Commodity', 'Commodity', 68),
('Quantum Commodity', 'Commodity', 141),
('Bio Options', 'Options', 227),
('Bitcoin', 'Cryptocurrency', 181),
('Cyber Networks', 'Stock', 324),
('Smart Commodity', 'Commodity', 3),
('NASDAQ Select ETF', 'ETF', 229),
('Asia Options', 'Options', 264),
('Ethcoin', 'Cryptocurrency', 316),
('Atlantic Solutions Bond 2yr', 'Bond', 127),
('Atlantic Options', 'Options', 128),
('Smart Corp Bond 8yr', 'Bond', 10),
('Bitcoin', 'Cryptocurrency', 334),
('Smart Options', 'Options', 123),
('Tech Futures', 'Futures', 28),
('Bitcoin', 'Cryptocurrency', 105),
('Bio Futures', 'Futures', 349),
('Euro Commodity', 'Commodity', 174),
('S&P Prime ETF', 'ETF', 312),
('American Healthcare', 'Stock', 260),
('Ethcoin', 'Cryptocurrency', 4),
('Litecoin', 'Cryptocurrency', 143),
('Tech Futures', 'Futures', 59),
('Alpine Options', 'Options', 313),
('Alpine Futures', 'Futures', 177),
('United Futures', 'Futures', 334),
('Digital Systems Bond 29yr', 'Bond', 84),
('Cyber Futures', 'Futures', 374),
('Bio Options', 'Options', 343),
('Quantum Commodity', 'Commodity', 308),
('Bio Commodity', 'Commodity', 80),
('Pacific Commodity', 'Commodity', 57),
('United Ltd', 'Stock', 134),
('Alpine Inc Bond 5yr', 'Bond', 257),
('United Corp Bond 19yr', 'Bond', 320);

INSERT INTO assets (name, asset_type, broker_id) VALUES
('Digital Futures', 'Futures', 43),
('Bio Commodity', 'Commodity', 80),
('Tech Commodity', 'Commodity', 18),
('Eco Energy', 'Stock', 76),
('Alpine Commodity', 'Commodity', 99),
('S&P Total ETF', 'ETF', 99),
('Bio Futures', 'Futures', 142),
('NASDAQ Select ETF', 'ETF', 112),
('NASDAQ Select ETF', 'ETF', 97),
('Tech Futures', 'Futures', 91),
('Bitcoin', 'Cryptocurrency', 139),
('Global Ltd', 'Stock', 138),
('DOW Total ETF', 'ETF', 36),
('American Options', 'Options', 8),
('Bitcoin', 'Cryptocurrency', 99),
('Tech Corp', 'Stock', 88),
('American Options', 'Options', 105),
('Litecoin', 'Cryptocurrency', 52),
('Eco Commodity', 'Commodity', 130),
('Cyber Group Bond 21yr', 'Bond', 74),
('Bio Options', 'Options', 42),
('Tech Futures', 'Futures', 39),
('Eco Futures', 'Futures', 127),
('Cyber Healthcare', 'Stock', 135),
('Euro Pharma Bond 26yr', 'Bond', 153),
('United Commodity', 'Commodity', 91),
('United Networks', 'Stock', 67),
('Digital Solutions', 'Stock', 28),
('United Tech Bond 20yr', 'Bond', 124),
('American Corp', 'Stock', 93),
('American Commodity', 'Commodity', 153),
('Quantum Solutions', 'Stock', 83),
('Ethcoin', 'Cryptocurrency', 81),
('Asia Commodity', 'Commodity', 26),
('Euro Solutions Bond 5yr', 'Bond', 16),
('Pacific Futures', 'Futures', 169),
('Atlantic Systems', 'Stock', 41),
('Eco Group', 'Stock', 122),
('DOW Total ETF', 'ETF', 118),
('Euro Futures', 'Futures', 121),
('Global Commodity', 'Commodity', 157),
('Bio Options', 'Options', 153),
('Digital Commodity', 'Commodity', 12),
('Cyber Futures', 'Futures', 106),
('NASDAQ Total ETF', 'ETF', 119),
('NASDAQ Select ETF', 'ETF', 160),
('Pacific Commodity', 'Commodity', 111),
('Bitcoin', 'Cryptocurrency', 49),
('NASDAQ Prime ETF', 'ETF', 179),
('Alpine Commodity', 'Commodity', 146),
('Bitcoin', 'Cryptocurrency', 17),
('Eco Options', 'Options', 5),
('NASDAQ Select ETF', 'ETF', 84),
('Global Commodity', 'Commodity', 177),
('American Ltd Bond 30yr', 'Bond', 186),
('Bio Solutions Bond 21yr', 'Bond', 92),
('Euro Options', 'Options', 46),
('Euro Futures', 'Futures', 154),
('Asia Options', 'Options', 186),
('Ethcoin', 'Cryptocurrency', 152),
('Quantum Inc', 'Stock', 83),
('Alpine Options', 'Options', 195),
('Quantum Commodity', 'Commodity', 153),
('Atlantic Futures', 'Futures', 18),
('Eco Communications', 'Stock', 26),
('Global Futures', 'Futures', 156),
('Pacific Inc', 'Stock', 103),
('Litecoin', 'Cryptocurrency', 75),
('Eco Corp Bond 22yr', 'Bond', 172),
('American Corp', 'Stock', 43),
('Smart Futures', 'Futures', 42),
('Tech Pharma Bond 7yr', 'Bond', 126),
('Ethcoin', 'Cryptocurrency', 37),
('NASDAQ Select ETF', 'ETF', 190),
('Pacific Commodity', 'Commodity', 7),
('Euro Options', 'Options', 184),
('DOW Select ETF', 'ETF', 100),
('Bitcoin', 'Cryptocurrency', 49),
('Smart Systems', 'Stock', 46),
('DOW Total ETF', 'ETF', 196),
('DOW Prime ETF', 'ETF', 63),
('Asia Systems', 'Stock', 65),
('Ethcoin', 'Cryptocurrency', 208),
('Bio Options', 'Options', 67),
('S&P Total ETF', 'ETF', 17),
('NASDAQ Select ETF', 'ETF', 196),
('Eco Commodity', 'Commodity', 53),
('Global Options', 'Options', 77),
('Ethcoin', 'Cryptocurrency', 45),
('Euro Futures', 'Futures', 106),
('Litecoin', 'Cryptocurrency', 12),
('Alpine Futures', 'Futures', 56),
('Atlantic Options', 'Options', 122),
('NASDAQ Select ETF', 'ETF', 25),
('Atlantic Healthcare', 'Stock', 74),
('Alpine Options', 'Options', 145),
('Ethcoin', 'Cryptocurrency', 175),
('DOW Total ETF', 'ETF', 17),
('NASDAQ Total ETF', 'ETF', 7),
('Asia Options', 'Options', 103),
('Global Options', 'Options', 169),
('American Options', 'Options', 27),
('Atlantic Pharma', 'Stock', 92),
('Cyber Futures', 'Futures', 62),
('American Media Bond 5yr', 'Bond', 9),
('Global Solutions', 'Stock', 70),
('S&P Total ETF', 'ETF', 137),
('Alpine Tech Bond 11yr', 'Bond', 145),
('United Futures', 'Futures', 195),
('DOW Total ETF', 'ETF', 227),
('Smart Commodity', 'Commodity', 57),
('S&P Select ETF', 'ETF', 190),
('Euro Futures', 'Futures', 213),
('Global Group', 'Stock', 137),
('Digital Commodity', 'Commodity', 200),
('Tech Options', 'Options', 101),
('Global Commodity', 'Commodity', 12),
('Tech Commodity', 'Commodity', 170),
('Bitcoin', 'Cryptocurrency', 45),
('Smart Solutions Bond 1yr', 'Bond', 227),
('Asia Options', 'Options', 79),
('Euro Futures', 'Futures', 171),
('Smart Commodity', 'Commodity', 236),
('Tech Pharma Bond 19yr', 'Bond', 53),
('Ethcoin', 'Cryptocurrency', 188);

INSERT INTO assets (name, asset_type, broker_id) VALUES
('Cyber Corp', 'Stock', 68),
('Quantum Inc', 'Stock', 82),
('United Pharma', 'Stock', 356),
('United Commodity', 'Commodity', 156),
('Cyber Futures', 'Futures', 326),
('Euro Media', 'Stock', 105),
('DOW Total ETF', 'ETF', 214),
('Global Energy Bond 7yr', 'Bond', 75),
('Alpine Networks Bond 27yr', 'Bond', 380),
('Litecoin', 'Cryptocurrency', 149),
('NASDAQ Select ETF', 'ETF', 109),
('Global Commodity', 'Commodity', 131),
('Quantum Futures', 'Futures', 72),
('Asia Commodity', 'Commodity', 377),
('Pacific Futures', 'Futures', 174),
('DOW Select ETF', 'ETF', 276),
('Litecoin', 'Cryptocurrency', 81),
('Alpine Pharma', 'Stock', 342),
('DOW Total ETF', 'ETF', 154),
('Asia Group Bond 26yr', 'Bond', 193),
('Pacific Media', 'Stock', 360),
('American Commodity', 'Commodity', 108),
('Bitcoin', 'Cryptocurrency', 351),
('Cyber Commodity', 'Commodity', 265),
('NASDAQ Select ETF', 'ETF', 82),
('Tech Futures', 'Futures', 10),
('Digital Ltd', 'Stock', 252),
('Quantum Futures', 'Futures', 145),
('DOW Prime ETF', 'ETF', 235),
('NASDAQ Prime ETF', 'ETF', 69),
('Bitcoin', 'Cryptocurrency', 253),
('NASDAQ Select ETF', 'ETF', 78),
('Alpine Group Bond 8yr', 'Bond', 216),
('American Futures', 'Futures', 26),
('Digital Futures', 'Futures', 236),
('S&P Total ETF', 'ETF', 110),
('Digital Industries Bond 3yr', 'Bond', 370),
('Euro Networks', 'Stock', 252),
('Litecoin', 'Cryptocurrency', 97),
('S&P Prime ETF', 'ETF', 267),
('Alpine Commodity', 'Commodity', 173),
('Digital Futures', 'Futures', 126),
('Digital Futures', 'Futures', 355),
('Ethcoin', 'Cryptocurrency', 336),
('S&P Total ETF', 'ETF', 207),
('American Futures', 'Futures', 148),
('DOW Select ETF', 'ETF', 280),
('Atlantic Options', 'Options', 425),
('Cyber Group Bond 2yr', 'Bond', 292),
('Pacific Commodity', 'Commodity', 180),
('American Futures', 'Futures', 20),
('Smart Ltd', 'Stock', 424),
('Euro Futures', 'Futures', 94),
('Atlantic Inc Bond 25yr', 'Bond', 15),
('Euro Ltd Bond 15yr', 'Bond', 50),
('Litecoin', 'Cryptocurrency', 223),
('Smart Futures', 'Futures', 164),
('DOW Prime ETF', 'ETF', 121),
('Cyber Futures', 'Futures', 434),
('DOW Select ETF', 'ETF', 40),
('DOW Prime ETF', 'ETF', 356),
('Quantum Futures', 'Futures', 288),
('Global Futures', 'Futures', 245),
('Pacific Pharma', 'Stock', 213),
('United Futures', 'Futures', 74),
('Litecoin', 'Cryptocurrency', 164),
('Asia Commodity', 'Commodity', 75),
('Atlantic Commodity', 'Commodity', 449),
('Digital Group Bond 15yr', 'Bond', 92),
('Smart Group', 'Stock', 178),
('Asia Inc', 'Stock', 242),
('Tech Options', 'Options', 58),
('Digital Commodity', 'Commodity', 456),
('Quantum Options', 'Options', 373),
('Litecoin', 'Cryptocurrency', 264),
('Alpine Networks', 'Stock', 102),
('Bio Futures', 'Futures', 322),
('Euro Futures', 'Futures', 303),
('Tech Ltd Bond 12yr', 'Bond', 352),
('Smart Systems Bond 3yr', 'Bond', 65),
('Tech Options', 'Options', 383),
('Bio Options', 'Options', 303),
('United Pharma', 'Stock', 90),
('S&P Total ETF', 'ETF', 151),
('Bitcoin', 'Cryptocurrency', 373),
('Pacific Commodity', 'Commodity', 277),
('Bio Commodity', 'Commodity', 335),
('Litecoin', 'Cryptocurrency', 438),
('Pacific Energy', 'Stock', 254),
('Bitcoin', 'Cryptocurrency', 217),
('Tech Commodity', 'Commodity', 116),
('Euro Energy Bond 13yr', 'Bond', 393),
('United Options', 'Options', 473),
('S&P Select ETF', 'ETF', 420),
('Bio Options', 'Options', 174),
('Litecoin', 'Cryptocurrency', 464),
('Bitcoin', 'Cryptocurrency', 266),
('Cyber Solutions Bond 27yr', 'Bond', 301),
('Eco Commodity', 'Commodity', 332),
('American Industries Bond 12yr', 'Bond', 299),
('Eco Commodity', 'Commodity', 436),
('Bio Commodity', 'Commodity', 80),
('American Solutions Bond 26yr', 'Bond', 215),
('Pacific Systems Bond 9yr', 'Bond', 252),
('Global Communications', 'Stock', 490),
('Bio Corp Bond 21yr', 'Bond', 470),
('Alpine Commodity', 'Commodity', 197),
('Alpine Commodity', 'Commodity', 308),
('Smart Commodity', 'Commodity', 106),
('Bitcoin', 'Cryptocurrency', 177),
('Bio Futures', 'Futures', 309),
('Quantum Networks Bond 26yr', 'Bond', 63),
('United Commodity', 'Commodity', 116),
('Eco Ltd Bond 1yr', 'Bond', 61),
('Ethcoin', 'Cryptocurrency', 204),
('Eco Options', 'Options', 313),
('Atlantic Options', 'Options', 461),
('Quantum Group', 'Stock', 432),
('Smart Futures', 'Futures', 178),
('Cyber Options', 'Options', 51),
('Litecoin', 'Cryptocurrency', 490),
('Litecoin', 'Cryptocurrency', 393),
('Euro Options', 'Options', 455),
('Smart Inc', 'Stock', 406),
('Litecoin', 'Cryptocurrency', 424);

INSERT INTO assets (name, asset_type, broker_id) VALUES
('Bio Media', 'Stock', 370),
('Euro Healthcare', 'Stock', 209),
('Atlantic Futures', 'Futures', 175),
('Cyber Options', 'Options', 54),
('Bitcoin', 'Cryptocurrency', 63),
('Atlantic Futures', 'Futures', 311),
('Tech Options', 'Options', 308),
('Pacific Solutions', 'Stock', 246),
('Pacific Options', 'Options', 26),
('S&P Select ETF', 'ETF', 120),
('Digital Networks', 'Stock', 404),
('Ethcoin', 'Cryptocurrency', 13),
('Alpine Commodity', 'Commodity', 79),
('Eco Commodity', 'Commodity', 442),
('Cyber Solutions Bond 28yr', 'Bond', 187),
('NASDAQ Select ETF', 'ETF', 229),
('Tech Commodity', 'Commodity', 331),
('American Futures', 'Futures', 212),
('Eco Futures', 'Futures', 23),
('Bitcoin', 'Cryptocurrency', 349),
('Global Futures', 'Futures', 392),
('Pacific Systems', 'Stock', 218),
('Digital Futures', 'Futures', 278),
('Tech Commodity', 'Commodity', 274),
('Bitcoin', 'Cryptocurrency', 217),
('Bitcoin', 'Cryptocurrency', 463),
('American Corp Bond 26yr', 'Bond', 405),
('Cyber Corp Bond 28yr', 'Bond', 115),
('United Healthcare', 'Stock', 50),
('Euro Commodity', 'Commodity', 181),
('NASDAQ Select ETF', 'ETF', 35),
('S&P Select ETF', 'ETF', 98),
('Quantum Options', 'Options', 526),
('Litecoin', 'Cryptocurrency', 48),
('Quantum Futures', 'Futures', 110),
('United Media', 'Stock', 236),
('Global Options', 'Options', 104),
('Pacific Futures', 'Futures', 32),
('United Futures', 'Futures', 142),
('Bio Ltd', 'Stock', 18),
('Alpine Futures', 'Futures', 289),
('Alpine Inc', 'Stock', 502),
('American Futures', 'Futures', 315),
('Global Corp Bond 18yr', 'Bond', 308),
('Alpine Futures', 'Futures', 371),
('S&P Total ETF', 'ETF', 130),
('Quantum Communications Bond 26yr', 'Bond', 34),
('Litecoin', 'Cryptocurrency', 471),
('Bio Commodity', 'Commodity', 193),
('Cyber Options', 'Options', 371),
('Cyber Commodity', 'Commodity', 526),
('Bitcoin', 'Cryptocurrency', 306),
('Atlantic Options', 'Options', 392),
('American Futures', 'Futures', 211),
('Tech Group', 'Stock', 481),
('Global Commodity', 'Commodity', 228),
('DOW Total ETF', 'ETF', 482),
('Euro Commodity', 'Commodity', 281),
('Atlantic Group Bond 15yr', 'Bond', 30),
('American Options', 'Options', 315),
('Global Futures', 'Futures', 523),
('S&P Total ETF', 'ETF', 58),
('Ethcoin', 'Cryptocurrency', 408),
('Bitcoin', 'Cryptocurrency', 96),
('Quantum Options', 'Options', 272),
('Eco Futures', 'Futures', 321),
('Ethcoin', 'Cryptocurrency', 562),
('Pacific Energy', 'Stock', 324),
('Atlantic Energy', 'Stock', 505),
('United Commodity', 'Commodity', 378),
('Euro Futures', 'Futures', 354),
('Euro Commodity', 'Commodity', 262),
('Global Futures', 'Futures', 411),
('American Healthcare', 'Stock', 311),
('Ethcoin', 'Cryptocurrency', 531),
('Atlantic Commodity', 'Commodity', 393),
('NASDAQ Total ETF', 'ETF', 346),
('Pacific Solutions Bond 18yr', 'Bond', 188),
('Pacific Media Bond 14yr', 'Bond', 531),
('Euro Commodity', 'Commodity', 353),
('American Networks Bond 23yr', 'Bond', 73),
('Eco Commodity', 'Commodity', 144),
('Bio Options', 'Options', 374),
('Asia Commodity', 'Commodity', 98),
('Global Options', 'Options', 526),
('Litecoin', 'Cryptocurrency', 70),
('Alpine Inc Bond 15yr', 'Bond', 500),
('Ethcoin', 'Cryptocurrency', 155),
('Ethcoin', 'Cryptocurrency', 304),
('Alpine Pharma Bond 25yr', 'Bond', 372),
('Asia Communications', 'Stock', 288),
('Digital Futures', 'Futures', 321),
('Quantum Options', 'Options', 198),
('S&P Prime ETF', 'ETF', 542),
('Alpine Futures', 'Futures', 380),
('S&P Select ETF', 'ETF', 74),
('Alpine Options', 'Options', 478),
('Asia Futures', 'Futures', 499),
('American Futures', 'Futures', 458),
('Pacific Futures', 'Futures', 152),
('Quantum Energy Bond 1yr', 'Bond', 317),
('Cyber Options', 'Options', 283),
('Ethcoin', 'Cryptocurrency', 206),
('Cyber Commodity', 'Commodity', 174),
('Quantum Options', 'Options', 197),
('NASDAQ Prime ETF', 'ETF', 397),
('Asia Futures', 'Futures', 553),
('Quantum Options', 'Options', 60),
('DOW Prime ETF', 'ETF', 196),
('Asia Ltd', 'Stock', 34),
('United Inc Bond 25yr', 'Bond', 306),
('Smart Media Bond 6yr', 'Bond', 231),
('Litecoin', 'Cryptocurrency', 261),
('Eco Communications', 'Stock', 569),
('United Futures', 'Futures', 594),
('American Media', 'Stock', 314),
('Asia Options', 'Options', 45),
('Bio Communications', 'Stock', 493),
('Quantum Ltd Bond 28yr', 'Bond', 236),
('NASDAQ Prime ETF', 'ETF', 130),
('American Options', 'Options', 158),
('American Options', 'Options', 464),
('Eco Commodity', 'Commodity', 89),
('S&P Prime ETF', 'ETF', 176),
('Atlantic Futures', 'Futures', 142);

INSERT INTO assets (name, asset_type, broker_id) VALUES
('American Futures', 'Futures', 52),
('Ethcoin', 'Cryptocurrency', 582),
('Asia Networks', 'Stock', 314),
('NASDAQ Select ETF', 'ETF', 482),
('Alpine Commodity', 'Commodity', 502),
('Smart Healthcare', 'Stock', 21),
('Global Options', 'Options', 86),
('Litecoin', 'Cryptocurrency', 373),
('Alpine Commodity', 'Commodity', 22),
('Tech Pharma', 'Stock', 299),
('Global Options', 'Options', 551),
('Asia Futures', 'Futures', 592),
('Asia Group', 'Stock', 146),
('Quantum Commodity', 'Commodity', 538),
('Bitcoin', 'Cryptocurrency', 6),
('Smart Futures', 'Futures', 497),
('Bio Ltd', 'Stock', 550),
('S&P Select ETF', 'ETF', 442),
('Bio Commodity', 'Commodity', 411),
('Global Options', 'Options', 583),
('Global Industries Bond 21yr', 'Bond', 584),
('Atlantic Commodity', 'Commodity', 363),
('Asia Pharma Bond 12yr', 'Bond', 454),
('Cyber Futures', 'Futures', 194),
('NASDAQ Select ETF', 'ETF', 384),
('Smart Futures', 'Futures', 359),
('S&P Prime ETF', 'ETF', 571),
('Bitcoin', 'Cryptocurrency', 600),
('Bitcoin', 'Cryptocurrency', 342),
('Alpine Commodity', 'Commodity', 637),
('Ethcoin', 'Cryptocurrency', 70),
('Smart Futures', 'Futures', 627),
('Bio Tech Bond 16yr', 'Bond', 225),
('Digital Futures', 'Futures', 247),
('Bio Futures', 'Futures', 347),
('Asia Options', 'Options', 105),
('Tech Corp Bond 6yr', 'Bond', 664),
('S&P Total ETF', 'ETF', 446),
('Atlantic Options', 'Options', 12),
('Alpine Corp Bond 20yr', 'Bond', 284),
('United Pharma Bond 13yr', 'Bond', 332),
('NASDAQ Total ETF', 'ETF', 576),
('Bio Futures', 'Futures', 560),
('DOW Select ETF', 'ETF', 167),
('Bio Futures', 'Futures', 299),
('S&P Prime ETF', 'ETF', 491),
('DOW Total ETF', 'ETF', 417),
('Global Corp Bond 6yr', 'Bond', 340),
('Cyber Futures', 'Futures', 277),
('Global Futures', 'Futures', 228),
('Bitcoin', 'Cryptocurrency', 572),
('Pacific Communications', 'Stock', 345),
('Euro Systems', 'Stock', 536),
('United Options', 'Options', 642),
('United Networks Bond 23yr', 'Bond', 466),
('Bio Media', 'Stock', 545),
('Euro Options', 'Options', 355),
('NASDAQ Prime ETF', 'ETF', 538),
('Litecoin', 'Cryptocurrency', 299),
('Eco Commodity', 'Commodity', 247),
('Ethcoin', 'Cryptocurrency', 482),
('Atlantic Futures', 'Futures', 219),
('Global Futures', 'Futures', 655),
('NASDAQ Select ETF', 'ETF', 650),
('Bitcoin', 'Cryptocurrency', 664),
('Bitcoin', 'Cryptocurrency', 522),
('S&P Total ETF', 'ETF', 488),
('United Healthcare', 'Stock', 613),
('Alpine Futures', 'Futures', 232),
('Smart Commodity', 'Commodity', 259),
('S&P Total ETF', 'ETF', 161),
('Digital Industries', 'Stock', 450),
('Euro Tech', 'Stock', 260),
('Quantum Futures', 'Futures', 405),
('Cyber Corp', 'Stock', 388),
('American Group', 'Stock', 183),
('Alpine Solutions Bond 22yr', 'Bond', 99),
('NASDAQ Select ETF', 'ETF', 268),
('DOW Select ETF', 'ETF', 377),
('Asia Options', 'Options', 376),
('Asia Media', 'Stock', 467),
('Asia Commodity', 'Commodity', 61),
('DOW Select ETF', 'ETF', 134),
('Global Healthcare Bond 3yr', 'Bond', 587),
('Bio Pharma', 'Stock', 541),
('Ethcoin', 'Cryptocurrency', 636),
('United Options', 'Options', 671),
('Asia Options', 'Options', 476),
('Digital Commodity', 'Commodity', 508),
('Digital Commodity', 'Commodity', 200),
('Eco Futures', 'Futures', 311),
('Tech Industries', 'Stock', 305),
('Ethcoin', 'Cryptocurrency', 553),
('American Options', 'Options', 148),
('Tech Energy Bond 30yr', 'Bond', 600),
('Bio Options', 'Options', 656),
('Bio Corp', 'Stock', 683),
('Cyber Options', 'Options', 594),
('Asia Commodity', 'Commodity', 448),
('Digital Options', 'Options', 153),
('Pacific Commodity', 'Commodity', 101),
('S&P Prime ETF', 'ETF', 414),
('Litecoin', 'Cryptocurrency', 419),
('Bio Futures', 'Futures', 30),
('DOW Total ETF', 'ETF', 535),
('Global Options', 'Options', 549),
('DOW Select ETF', 'ETF', 487),
('DOW Total ETF', 'ETF', 481),
('Cyber Options', 'Options', 136),
('Smart Options', 'Options', 39),
('Litecoin', 'Cryptocurrency', 125),
('Tech Commodity', 'Commodity', 497),
('Global Networks', 'Stock', 164),
('American Systems Bond 28yr', 'Bond', 266),
('Pacific Futures', 'Futures', 333),
('Litecoin', 'Cryptocurrency', 505),
('Digital Communications', 'Stock', 121),
('Bio Options', 'Options', 349),
('Smart Futures', 'Futures', 524),
('Bio Commodity', 'Commodity', 716),
('Quantum Commodity', 'Commodity', 258),
('Smart Options', 'Options', 324),
('Tech Energy', 'Stock', 36),
('Euro Futures', 'Futures', 492),
('Litecoin', 'Cryptocurrency', 665);

INSERT INTO assets (name, asset_type, broker_id) VALUES
('Alpine Commodity', 'Commodity', 656),
('Digital Commodity', 'Commodity', 387),
('S&P Total ETF', 'ETF', 755),
('Quantum Group Bond 9yr', 'Bond', 547),
('Smart Options', 'Options', 512),
('Quantum Options', 'Options', 685),
('United Futures', 'Futures', 42),
('Pacific Futures', 'Futures', 139),
('Cyber Commodity', 'Commodity', 4),
('Alpine Futures', 'Futures', 621),
('Litecoin', 'Cryptocurrency', 750),
('Litecoin', 'Cryptocurrency', 162),
('Quantum Options', 'Options', 17),
('Bio Options', 'Options', 422),
('Bitcoin', 'Cryptocurrency', 155),
('Global Commodity', 'Commodity', 287),
('Tech Group', 'Stock', 570),
('NASDAQ Prime ETF', 'ETF', 203),
('Quantum Media Bond 13yr', 'Bond', 617),
('Bio Communications Bond 25yr', 'Bond', 708),
('Asia Tech', 'Stock', 781),
('Bio Ltd Bond 28yr', 'Bond', 419),
('Digital Networks', 'Stock', 580),
('Eco Networks', 'Stock', 430),
('Quantum Networks', 'Stock', 359),
('NASDAQ Total ETF', 'ETF', 497),
('Tech Media', 'Stock', 208),
('Global Media Bond 20yr', 'Bond', 585),
('Eco Energy', 'Stock', 756),
('Global Futures', 'Futures', 460),
('Alpine Futures', 'Futures', 771),
('Euro Corp Bond 17yr', 'Bond', 692),
('NASDAQ Prime ETF', 'ETF', 424),
('Digital Options', 'Options', 611),
('Euro Futures', 'Futures', 65),
('NASDAQ Prime ETF', 'ETF', 422),
('Smart Futures', 'Futures', 786),
('Alpine Commodity', 'Commodity', 786),
('Global Energy', 'Stock', 457),
('Smart Commodity', 'Commodity', 766),
('NASDAQ Total ETF', 'ETF', 427),
('Eco Options', 'Options', 190),
('Quantum Futures', 'Futures', 331),
('DOW Total ETF', 'ETF', 686),
('Litecoin', 'Cryptocurrency', 14),
('S&P Select ETF', 'ETF', 505),
('Bitcoin', 'Cryptocurrency', 172),
('Eco Media Bond 4yr', 'Bond', 670),
('DOW Prime ETF', 'ETF', 448),
('Quantum Futures', 'Futures', 114),
('Cyber Commodity', 'Commodity', 308),
('Litecoin', 'Cryptocurrency', 511),
('Atlantic Corp', 'Stock', 464),
('Alpine Solutions Bond 3yr', 'Bond', 739),
('American Energy', 'Stock', 89),
('Bio Tech', 'Stock', 542),
('Smart Options', 'Options', 123),
('United Options', 'Options', 238),
('Eco Group Bond 21yr', 'Bond', 266),
('American Futures', 'Futures', 195),
('DOW Select ETF', 'ETF', 158),
('Euro Futures', 'Futures', 382),
('Pacific Options', 'Options', 340),
('Cyber Group', 'Stock', 361),
('Asia Media Bond 26yr', 'Bond', 686),
('Eco Futures', 'Futures', 416),
('DOW Total ETF', 'ETF', 400),
('Pacific Solutions', 'Stock', 427),
('S&P Total ETF', 'ETF', 188),
('Tech Options', 'Options', 352),
('Bitcoin', 'Cryptocurrency', 688),
('Litecoin', 'Cryptocurrency', 663),
('Atlantic Tech', 'Stock', 202),
('Cyber Communications Bond 9yr', 'Bond', 679),
('Bitcoin', 'Cryptocurrency', 560),
('S&P Total ETF', 'ETF', 430),
('Bitcoin', 'Cryptocurrency', 732),
('Asia Communications', 'Stock', 306),
('Digital Commodity', 'Commodity', 258),
('Ethcoin', 'Cryptocurrency', 745),
('Digital Options', 'Options', 285),
('Euro Futures', 'Futures', 218),
('Ethcoin', 'Cryptocurrency', 96),
('Bitcoin', 'Cryptocurrency', 81),
('Eco Options', 'Options', 752),
('Litecoin', 'Cryptocurrency', 509),
('Bitcoin', 'Cryptocurrency', 484),
('DOW Select ETF', 'ETF', 360),
('United Futures', 'Futures', 628),
('Pacific Commodity', 'Commodity', 809),
('Euro Futures', 'Futures', 848),
('Pacific Futures', 'Futures', 281),
('DOW Select ETF', 'ETF', 678),
('NASDAQ Select ETF', 'ETF', 636),
('Cyber Commodity', 'Commodity', 695),
('NASDAQ Select ETF', 'ETF', 603),
('Global Options', 'Options', 830),
('Smart Options', 'Options', 802),
('Eco Systems', 'Stock', 499),
('Pacific Options', 'Options', 270),
('Smart Options', 'Options', 47),
('Bio Networks', 'Stock', 713),
('Ethcoin', 'Cryptocurrency', 780),
('Bio Industries Bond 22yr', 'Bond', 705),
('Cyber Commodity', 'Commodity', 688),
('DOW Select ETF', 'ETF', 506),
('Quantum Futures', 'Futures', 524),
('Quantum Commodity', 'Commodity', 430),
('DOW Total ETF', 'ETF', 790),
('Tech Commodity', 'Commodity', 194),
('NASDAQ Select ETF', 'ETF', 35),
('NASDAQ Total ETF', 'ETF', 236),
('Eco Options', 'Options', 759),
('Bitcoin', 'Cryptocurrency', 211),
('Euro Energy Bond 4yr', 'Bond', 566),
('Eco Options', 'Options', 559),
('DOW Prime ETF', 'ETF', 633),
('United Pharma Bond 7yr', 'Bond', 648),
('S&P Total ETF', 'ETF', 81),
('Euro Commodity', 'Commodity', 350),
('Tech Options', 'Options', 337),
('American Futures', 'Futures', 823),
('NASDAQ Prime ETF', 'ETF', 439),
('Smart Futures', 'Futures', 734),
('Quantum Group', 'Stock', 771);

INSERT INTO assets (name, asset_type, broker_id) VALUES
('DOW Total ETF', 'ETF', 76),
('Smart Commodity', 'Commodity', 19),
('S&P Select ETF', 'ETF', 140),
('Bio Commodity', 'Commodity', 222),
('Ethcoin', 'Cryptocurrency', 680),
('Quantum Options', 'Options', 186),
('Pacific Futures', 'Futures', 698),
('American Media', 'Stock', 353),
('Euro Networks Bond 7yr', 'Bond', 440),
('Ethcoin', 'Cryptocurrency', 783),
('Tech Systems', 'Stock', 772),
('American Healthcare Bond 12yr', 'Bond', 438),
('Euro Options', 'Options', 144),
('Pacific Ltd Bond 6yr', 'Bond', 234),
('Euro Futures', 'Futures', 514),
('Quantum Commodity', 'Commodity', 119),
('Atlantic Inc', 'Stock', 585),
('Asia Options', 'Options', 552),
('Quantum Commodity', 'Commodity', 756),
('S&P Total ETF', 'ETF', 10),
('Ethcoin', 'Cryptocurrency', 74),
('Alpine Commodity', 'Commodity', 764),
('Bio Networks Bond 15yr', 'Bond', 515),
('Ethcoin', 'Cryptocurrency', 832),
('Digital Industries', 'Stock', 282),
('American Inc Bond 9yr', 'Bond', 9),
('Smart Networks Bond 11yr', 'Bond', 383),
('Euro Futures', 'Futures', 559),
('Quantum Commodity', 'Commodity', 909),
('Litecoin', 'Cryptocurrency', 272),
('Global Corp Bond 1yr', 'Bond', 557),
('Euro Commodity', 'Commodity', 846),
('S&P Total ETF', 'ETF', 178),
('Bitcoin', 'Cryptocurrency', 743),
('Tech Futures', 'Futures', 232),
('NASDAQ Prime ETF', 'ETF', 175),
('Bitcoin', 'Cryptocurrency', 869),
('Bitcoin', 'Cryptocurrency', 716),
('Quantum Commodity', 'Commodity', 700),
('Asia Networks', 'Stock', 372),
('NASDAQ Prime ETF', 'ETF', 206),
('Quantum Futures', 'Futures', 529),
('Asia Commodity', 'Commodity', 16),
('Litecoin', 'Cryptocurrency', 481),
('American Tech Bond 5yr', 'Bond', 361),
('Tech Commodity', 'Commodity', 912),
('United Options', 'Options', 828),
('S&P Prime ETF', 'ETF', 376),
('Tech Healthcare', 'Stock', 399),
('S&P Select ETF', 'ETF', 347),
('Quantum Options', 'Options', 85),
('Digital Inc Bond 7yr', 'Bond', 371),
('NASDAQ Select ETF', 'ETF', 756),
('Euro Inc Bond 5yr', 'Bond', 762),
('Pacific Commodity', 'Commodity', 63),
('Quantum Media Bond 16yr', 'Bond', 198),
('Global Commodity', 'Commodity', 846),
('Ethcoin', 'Cryptocurrency', 148),
('Pacific Solutions', 'Stock', 211),
('Eco Healthcare', 'Stock', 115),
('Alpine Communications', 'Stock', 91),
('Pacific Group Bond 21yr', 'Bond', 440),
('Global Healthcare', 'Stock', 627),
('United Options', 'Options', 84),
('Atlantic Systems', 'Stock', 463),
('NASDAQ Total ETF', 'ETF', 584),
('Litecoin', 'Cryptocurrency', 727),
('Digital Tech', 'Stock', 695),
('Bio Pharma', 'Stock', 758),
('Pacific Commodity', 'Commodity', 899),
('Asia Inc', 'Stock', 612),
('Pacific Communications Bond 16yr', 'Bond', 522),
('DOW Prime ETF', 'ETF', 829),
('Bio Futures', 'Futures', 853),
('Asia Futures', 'Futures', 845),
('Cyber Solutions', 'Stock', 353),
('Quantum Futures', 'Futures', 536),
('Eco Futures', 'Futures', 303),
('Asia Commodity', 'Commodity', 85),
('Ethcoin', 'Cryptocurrency', 30),
('Alpine Commodity', 'Commodity', 189),
('Eco Futures', 'Futures', 303),
('United Options', 'Options', 196),
('Euro Pharma Bond 11yr', 'Bond', 365),
('Global Pharma', 'Stock', 17),
('Ethcoin', 'Cryptocurrency', 465),
('Digital Futures', 'Futures', 358),
('Asia Communications', 'Stock', 408),
('NASDAQ Total ETF', 'ETF', 709),
('Litecoin', 'Cryptocurrency', 785),
('Ethcoin', 'Cryptocurrency', 489),
('S&P Total ETF', 'ETF', 649),
('Litecoin', 'Cryptocurrency', 460),
('Global Commodity', 'Commodity', 292),
('Smart Options', 'Options', 442),
('Tech Industries Bond 6yr', 'Bond', 109),
('Atlantic Commodity', 'Commodity', 435),
('Ethcoin', 'Cryptocurrency', 896),
('Alpine Group Bond 19yr', 'Bond', 981),
('NASDAQ Prime ETF', 'ETF', 142),
('Global Options', 'Options', 617),
('Eco Options', 'Options', 721),
('Eco Healthcare', 'Stock', 496),
('DOW Total ETF', 'ETF', 133),
('Pacific Commodity', 'Commodity', 908),
('United Futures', 'Futures', 450),
('Alpine Commodity', 'Commodity', 138),
('Asia Options', 'Options', 609),
('Asia Futures', 'Futures', 267),
('Asia Solutions Bond 11yr', 'Bond', 681),
('Quantum Corp Bond 12yr', 'Bond', 7),
('Digital Futures', 'Futures', 68),
('S&P Total ETF', 'ETF', 420),
('Cyber Options', 'Options', 318),
('Pacific Pharma Bond 5yr', 'Bond', 724),
('Asia Communications', 'Stock', 69),
('Tech Ltd Bond 15yr', 'Bond', 33),
('Pacific Energy Bond 19yr', 'Bond', 469),
('Alpine Pharma Bond 8yr', 'Bond', 251),
('Quantum Options', 'Options', 867),
('DOW Total ETF', 'ETF', 449),
('Smart Energy', 'Stock', 433),
('Alpine Healthcare', 'Stock', 504),
('Asia Systems', 'Stock', 869),
('Cyber Futures', 'Futures', 886);

